apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: koney
    app.kubernetes.io/managed-by: kustomize
  name: alert-forwarder-service
  namespace: system
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    control-plane: controller-manager
