# permissions for end users to edit deceptionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: koney
    app.kubernetes.io/managed-by: kustomize
  name: deceptionpolicy-editor-role
rules:
- apiGroups:
  - research.dynatrace.com
  resources:
  - deceptionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - research.dynatrace.com
  resources:
  - deceptionpolicies/status
  verbs:
  - get
