# permissions for end users to view deceptionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: koney
    app.kubernetes.io/managed-by: kustomize
  name: deceptionpolicy-viewer-role
rules:
- apiGroups:
  - research.dynatrace.com
  resources:
  - deceptionpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - research.dynatrace.com
  resources:
  - deceptionpolicies/status
  verbs:
  - get
