apiVersion: apps/v1
kind: Deployment
metadata:
  name: koney-demo-deployment
  namespace: koney-demo
  labels:
    demo.koney/honeytoken: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: koney-demo-pod
  template:
    metadata:
      labels:
        app: koney-demo-pod
        demo.koney/honeytoken: "true"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
        - name: alpine
          image: alpine
          command: ["/bin/sh", "-c", 'trap "exit 0" SIGTERM SIGINT SIGKILL; /bin/sleep infinity & wait']
