apiVersion: v1
kind: Pod
metadata:
  name: koney-demo-pod
  namespace: koney-demo
  labels:
    demo.koney/honeytoken: "true"
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c", 'trap "exit 0" SIGTERM SIGINT SIGKILL; /bin/sleep infinity & wait']
